/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as QuickBuyRouteImport } from './routes/quick-buy'
import { Route as PremiumRouteImport } from './routes/premium'
import { Route as MarketRouteImport } from './routes/market'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as CommunityRouteImport } from './routes/community'
import { Route as IndexRouteImport } from './routes/index'
import { Route as MatchesIndexRouteImport } from './routes/matches.index'
import { Route as ProfileUsernameRouteImport } from './routes/profile.$username'
import { Route as MatchesMatchIdRouteImport } from './routes/matches.$matchId'
import { Route as MarketCreateRouteImport } from './routes/market.create'
import { Route as MarketIdRouteImport } from './routes/market.$id'
import { Route as ApiAuthSteamRouteImport } from './routes/api/auth/steam'
import { Route as ApiAuthLogoutRouteImport } from './routes/api/auth/logout'
import { Route as ApiAuthSteamReturnRouteImport } from './routes/api/auth/steam.return'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const QuickBuyRoute = QuickBuyRouteImport.update({
  id: '/quick-buy',
  path: '/quick-buy',
  getParentRoute: () => rootRouteImport,
} as any)
const PremiumRoute = PremiumRouteImport.update({
  id: '/premium',
  path: '/premium',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketRoute = MarketRouteImport.update({
  id: '/market',
  path: '/market',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const CommunityRoute = CommunityRouteImport.update({
  id: '/community',
  path: '/community',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const MatchesIndexRoute = MatchesIndexRouteImport.update({
  id: '/matches/',
  path: '/matches/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileUsernameRoute = ProfileUsernameRouteImport.update({
  id: '/profile/$username',
  path: '/profile/$username',
  getParentRoute: () => rootRouteImport,
} as any)
const MatchesMatchIdRoute = MatchesMatchIdRouteImport.update({
  id: '/matches/$matchId',
  path: '/matches/$matchId',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketCreateRoute = MarketCreateRouteImport.update({
  id: '/create',
  path: '/create',
  getParentRoute: () => MarketRoute,
} as any)
const MarketIdRoute = MarketIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => MarketRoute,
} as any)
const ApiAuthSteamRoute = ApiAuthSteamRouteImport.update({
  id: '/api/auth/steam',
  path: '/api/auth/steam',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthLogoutRoute = ApiAuthLogoutRouteImport.update({
  id: '/api/auth/logout',
  path: '/api/auth/logout',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSteamReturnRoute = ApiAuthSteamReturnRouteImport.update({
  id: '/return',
  path: '/return',
  getParentRoute: () => ApiAuthSteamRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/community': typeof CommunityRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/market': typeof MarketRouteWithChildren
  '/premium': typeof PremiumRoute
  '/quick-buy': typeof QuickBuyRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/market/$id': typeof MarketIdRoute
  '/market/create': typeof MarketCreateRoute
  '/matches/$matchId': typeof MatchesMatchIdRoute
  '/profile/$username': typeof ProfileUsernameRoute
  '/matches/': typeof MatchesIndexRoute
  '/api/auth/logout': typeof ApiAuthLogoutRoute
  '/api/auth/steam': typeof ApiAuthSteamRouteWithChildren
  '/api/auth/steam/return': typeof ApiAuthSteamReturnRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/community': typeof CommunityRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/market': typeof MarketRouteWithChildren
  '/premium': typeof PremiumRoute
  '/quick-buy': typeof QuickBuyRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/market/$id': typeof MarketIdRoute
  '/market/create': typeof MarketCreateRoute
  '/matches/$matchId': typeof MatchesMatchIdRoute
  '/profile/$username': typeof ProfileUsernameRoute
  '/matches': typeof MatchesIndexRoute
  '/api/auth/logout': typeof ApiAuthLogoutRoute
  '/api/auth/steam': typeof ApiAuthSteamRouteWithChildren
  '/api/auth/steam/return': typeof ApiAuthSteamReturnRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/community': typeof CommunityRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/market': typeof MarketRouteWithChildren
  '/premium': typeof PremiumRoute
  '/quick-buy': typeof QuickBuyRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/market/$id': typeof MarketIdRoute
  '/market/create': typeof MarketCreateRoute
  '/matches/$matchId': typeof MatchesMatchIdRoute
  '/profile/$username': typeof ProfileUsernameRoute
  '/matches/': typeof MatchesIndexRoute
  '/api/auth/logout': typeof ApiAuthLogoutRoute
  '/api/auth/steam': typeof ApiAuthSteamRouteWithChildren
  '/api/auth/steam/return': typeof ApiAuthSteamReturnRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/community'
    | '/dashboard'
    | '/login'
    | '/market'
    | '/premium'
    | '/quick-buy'
    | '/sitemap.xml'
    | '/market/$id'
    | '/market/create'
    | '/matches/$matchId'
    | '/profile/$username'
    | '/matches/'
    | '/api/auth/logout'
    | '/api/auth/steam'
    | '/api/auth/steam/return'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/community'
    | '/dashboard'
    | '/login'
    | '/market'
    | '/premium'
    | '/quick-buy'
    | '/sitemap.xml'
    | '/market/$id'
    | '/market/create'
    | '/matches/$matchId'
    | '/profile/$username'
    | '/matches'
    | '/api/auth/logout'
    | '/api/auth/steam'
    | '/api/auth/steam/return'
  id:
    | '__root__'
    | '/'
    | '/community'
    | '/dashboard'
    | '/login'
    | '/market'
    | '/premium'
    | '/quick-buy'
    | '/sitemap.xml'
    | '/market/$id'
    | '/market/create'
    | '/matches/$matchId'
    | '/profile/$username'
    | '/matches/'
    | '/api/auth/logout'
    | '/api/auth/steam'
    | '/api/auth/steam/return'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CommunityRoute: typeof CommunityRoute
  DashboardRoute: typeof DashboardRoute
  LoginRoute: typeof LoginRoute
  MarketRoute: typeof MarketRouteWithChildren
  PremiumRoute: typeof PremiumRoute
  QuickBuyRoute: typeof QuickBuyRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  MatchesMatchIdRoute: typeof MatchesMatchIdRoute
  ProfileUsernameRoute: typeof ProfileUsernameRoute
  MatchesIndexRoute: typeof MatchesIndexRoute
  ApiAuthLogoutRoute: typeof ApiAuthLogoutRoute
  ApiAuthSteamRoute: typeof ApiAuthSteamRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quick-buy': {
      id: '/quick-buy'
      path: '/quick-buy'
      fullPath: '/quick-buy'
      preLoaderRoute: typeof QuickBuyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/premium': {
      id: '/premium'
      path: '/premium'
      fullPath: '/premium'
      preLoaderRoute: typeof PremiumRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/market': {
      id: '/market'
      path: '/market'
      fullPath: '/market'
      preLoaderRoute: typeof MarketRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/community': {
      id: '/community'
      path: '/community'
      fullPath: '/community'
      preLoaderRoute: typeof CommunityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/matches/': {
      id: '/matches/'
      path: '/matches'
      fullPath: '/matches/'
      preLoaderRoute: typeof MatchesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile/$username': {
      id: '/profile/$username'
      path: '/profile/$username'
      fullPath: '/profile/$username'
      preLoaderRoute: typeof ProfileUsernameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/matches/$matchId': {
      id: '/matches/$matchId'
      path: '/matches/$matchId'
      fullPath: '/matches/$matchId'
      preLoaderRoute: typeof MatchesMatchIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/market/create': {
      id: '/market/create'
      path: '/create'
      fullPath: '/market/create'
      preLoaderRoute: typeof MarketCreateRouteImport
      parentRoute: typeof MarketRoute
    }
    '/market/$id': {
      id: '/market/$id'
      path: '/$id'
      fullPath: '/market/$id'
      preLoaderRoute: typeof MarketIdRouteImport
      parentRoute: typeof MarketRoute
    }
    '/api/auth/steam': {
      id: '/api/auth/steam'
      path: '/api/auth/steam'
      fullPath: '/api/auth/steam'
      preLoaderRoute: typeof ApiAuthSteamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/logout': {
      id: '/api/auth/logout'
      path: '/api/auth/logout'
      fullPath: '/api/auth/logout'
      preLoaderRoute: typeof ApiAuthLogoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/steam/return': {
      id: '/api/auth/steam/return'
      path: '/return'
      fullPath: '/api/auth/steam/return'
      preLoaderRoute: typeof ApiAuthSteamReturnRouteImport
      parentRoute: typeof ApiAuthSteamRoute
    }
  }
}

interface MarketRouteChildren {
  MarketIdRoute: typeof MarketIdRoute
  MarketCreateRoute: typeof MarketCreateRoute
}

const MarketRouteChildren: MarketRouteChildren = {
  MarketIdRoute: MarketIdRoute,
  MarketCreateRoute: MarketCreateRoute,
}

const MarketRouteWithChildren =
  MarketRoute._addFileChildren(MarketRouteChildren)

interface ApiAuthSteamRouteChildren {
  ApiAuthSteamReturnRoute: typeof ApiAuthSteamReturnRoute
}

const ApiAuthSteamRouteChildren: ApiAuthSteamRouteChildren = {
  ApiAuthSteamReturnRoute: ApiAuthSteamReturnRoute,
}

const ApiAuthSteamRouteWithChildren = ApiAuthSteamRoute._addFileChildren(
  ApiAuthSteamRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CommunityRoute: CommunityRoute,
  DashboardRoute: DashboardRoute,
  LoginRoute: LoginRoute,
  MarketRoute: MarketRouteWithChildren,
  PremiumRoute: PremiumRoute,
  QuickBuyRoute: QuickBuyRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  MatchesMatchIdRoute: MatchesMatchIdRoute,
  ProfileUsernameRoute: ProfileUsernameRoute,
  MatchesIndexRoute: MatchesIndexRoute,
  ApiAuthLogoutRoute: ApiAuthLogoutRoute,
  ApiAuthSteamRoute: ApiAuthSteamRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
